FROM --platform=linux/amd64 ubuntu:20.04 

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y cmake
ADD . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
