FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang cmake

COPY . /repo
WORKDIR /repo/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/install
RUN make -j8
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
ENV LD_LIBRARY_PATH=/install/lib
COPY --from=builder /repo/build/src/c2enc /
